version: '3'

services:
  server:
    image: edlingaona/example
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./db/survey.sqlite:/app/db/survey.sqlite
    environment:
      - NODE_ENV=production
    command: npm run start

